name = "block-quest"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"
script_name = "block-quest"

[env.production]
route = "blockquest.example.com/*"
vars = { ENVIRONMENT = "production" }